### ISSUE TITLE
daringfireball.net breaks when json formatter extension is enabled

### ISSUE THREAD

**Issue by davemyersworld** [rfletcher/safari-json-formatter#1]
please visit http://daringfireball.net/ to see the problem (toggle the extension on/off to view how it breaks)

**Comment by rfletcher** [comment]
Thanks for the report.  Sorry for the super late reply.  I was never notified by GitHub about new tickets.

This version of the extension injects its CSS into every page Safari loads.  At the early stage the extension was written I thought Safari did more sandboxing than that, and I just haven't gotten around to fixing the bug now that I know better.

I'm not sure how you came to find the extension, but now that I know people are using it I'll get a fix out quickly.  In the meantime, if you're still using the extension, you can just toggle it on and off as needed.

**Comment by rfletcher** [comment]
Fixed in 1.0.1.  Update with Safari's extensions preference pane, or download it directly: http://github.com/rfletcher/safari-json-formatter/downloads

**Comment by davemyersworld** [comment]
I found it via some blog that came out that listed safari extensions (launched just days after safari 5 was launched)

Anyway, its really helpful as I was working on debugging some json services, and this made life a lot easier... Thanks!

**Comment by pstinnett** [comment]
Thanks for the fix. I found it via a tweet.

**Comment by rfletcher** [comment]
Glad you guys have found it helpful.  Thanks for the bug report!
