### ISSUE TITLE
"Toggle Formatting" button has visual issue with rounded corners

### ISSUE THREAD

**Issue by nsforge** [rfletcher/safari-json-formatter#13]
In Safari 5.1.3, JSON Formatter 1.1, the toggle button's internal gradient doesn't have rounded corners. Adding the following CSS fixes it:

```
#toolbar li {
    border-radius: 4px;
}
```

**Comment by rfletcher** [comment]
Thanks, but this is because of a WebKit bug whose fix is included in the upcoming Safari 5.2.  `border-radius` and `overflow: hidden` will start doing the right thing once it's released.
