### ISSUE TITLE
Noticed that json formatter extension is causing incorrect fonts to load on certain sites

### ISSUE THREAD

**Issue by pstinnett** [rfletcher/safari-json-formatter#2]
Noticed that json formatter extension is causing incorrect fonts to load on certain sites. Specifically EliisLabs forums:

http://www.expressionengine.com/forums
http://www.mojomotor.com/forums
http://www.codeigniter.com/forums

**Comment by rfletcher** [comment]
Thanks for the report.  There is a CSS bug.  See issue #1.
