### ISSUE TITLE
Collapse/Expand nodes

### ISSUE THREAD

**Issue by erikhuisman** [rfletcher/safari-json-formatter#4]
For extra viewing pleasure on large datasets it might come in handy to be able to collapse and expand nodes. Look at firefox plugin "jsonview" for inspiration ;)

**Comment by ronnyandre** [comment]
Agreed. This is really functional.

**Comment by danhealy** [comment]
Huge +1

**Comment by rfletcher** [comment]
Added, mostly thanks to @daniels220's patch in issue #10.  I'll push a new version soon.
