### ISSUE TITLE
Can you ignore JSON in iframe?

### ISSUE THREAD

**Issue by nov** [rfletcher/safari-json-formatter#7]
I'm using jquery.upload in JSON format.
http://lagoscript.org/jquery/upload

This plugin changes the response body before jquery.upload get it, and jquery.upload fails to get JSON in its iframe for Ajax upload.

If this plugin can skip parsing JSON in iframe, it would be fixed.

**Comment by nov** [comment]
ps.
The last demo here uses json, and it fails only on Safari which has JSON Formatter.
http://lagoscript.org/jquery/upload/demo

**Comment by marksuman** [comment]
bump. we ran into this problem, too.

**Comment by rfletcher** [comment]
I've merged @bjhomer's patch from issue #8.  I'll push a new version soon.

**Comment by ijansch** [comment]
This actually breaks stuff for some users.. We are using an automated JSON api testing tool which renders the output of a selected request inside an iframe. We had the plugin installed to make sense of the output. With this fix we no longer get highlighting inside iframes. Ideally, this could be a setting maybe?

**Comment by joshuatbrown** [comment]
@ijansch I had a similar problem and opened #26
