### ISSUE TITLE
entity quotes cause formatting issues

### ISSUE THREAD

**Issue by dmorrow** [rfletcher/safari-json-formatter#9]
&quot; in content breaks formatting

{
    "example":"&quot;quoted content&quot;"
}

doesn't format correctly

**Comment by rfletcher** [comment]
The JSON in your report isn't valid, so I wouldn't expect that it would be handled correctly.  That said, I'm not sure if the JSON displayed above is exactly what you pasted, or if something got reformatted by GitHub.  Just in case, I tried this JSON, too:

``` json
{
  "example":"&quot;quoted content&quot;"
}
```

...but that was also formatted correctly.  Please reopen this issue if I've just misunderstood and there is a bug here.
